name: Build & Deploy to GAE

on:
  workflow_dispatch:
   inputs:
      choose_repository:
        required: false
        description: "Chooses which repositories workflow to run"
        type: string
      port_context:
        required: false
        description: "Details about the action and general context (blueprint, run id, etc...)"
        type: string
      hostname:
        required: false
        description: "hostnmae"
        type: string
      environment:
        required: false
        description: "production env"
        type: string
      provider:
        required: false
        description: "production env"
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ---------- FRONTEND BUILD ----------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build frontend
        working-directory: react-client
        run: |
          npm install
          npm run build
          # Copy frontend build into Spring Boot resources/static
          rm -rf ../spring-boot-server/src/main/resources/static/*
          cp -r build/* ../spring-boot-server/src/main/resources/static/ 

      # ---------- BACKEND BUILD ----------
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot App
        working-directory: spring-boot-server
        run: mvn clean package -DskipTests
    
      - name: Verify Build Artifact
        run: ls -R spring-boot-server

      # ---------- GCP DEPLOY ----------
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: myidpproject-469612   # replace with acttual GCP project
          deliverables: spring-boot-server/target/spring-boot-data-jpa-0.0.1-SNAPSHOT.jar
          promote: true
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        
      - name: Notify Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          baseUrl: https://api.getport.io
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            Application deployed successfully in Production environment. View it here http://${{fromJson(inputs.port_context).host}}:3000
          status: SUCCESS