name: Deploy Fullstack App to EC2

on:
  workflow_dispatch:
   inputs:
      choose_repository:
        required: false
        description: "Chooses which repositories workflow to run"
        type: string
      port_context:
        required: false
        description: "Details about the action and general context (blueprint, run id, etc...)"
        type: string
      hostname:
        required: false
        description: "hostnmae"
        type: string
      environment:
        required: false
        description: "production env"
        type: string
      provider:
        required: false
        description: "production env"
        type: string


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
     - name: Checkout repository
       uses: actions/checkout@v3

      # ---------- FRONTEND BUILD ----------
     - name: Setup Node.js
       uses: actions/setup-node@v3
       with:
          node-version: 18

     - name: Build frontend
       working-directory: react-client
       run: |
          npm install
          npm run build
          # Copy frontend build into Spring Boot resources/static
          rm -rf ../spring-boot-server/src/main/resources/static/*
          cp -r build/* ../spring-boot-server/src/main/resources/static/ 

      # ---------- BACKEND BUILD ----------
     - name: Setup JDK
       uses: actions/setup-java@v3
       with:
          java-version: '17'
          distribution: 'temurin'

     - name: Build Spring Boot App
       working-directory: spring-boot-server
       run: mvn clean package -DskipTests
      
     - name: List build outputs
       run: |
        ls -R react-client/build || echo "Frontend build missing"
        ls -R spring-boot-server/target || echo "Backend JAR missing"


      # ---------- DEPLOY ----------
     - name: Copy files to EC2
       uses: appleboy/scp-action@v0.1.7
       with:
          host: ${{ inputs.hostname}}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: |
            react-client/build/** 
            spring-boot-server/target/spring-boot-data-jpa-0.0.1-SNAPSHOT.jar
          target: /home/${{ secrets.EC2_USERNAME }}/fullstk-app

     - name: Restart services on EC2
       uses: appleboy/ssh-action@v0.1.10
       with:
          host: ${{inputs.hostname}}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Deploy frontend
            sudo rm -rf /var/www/frontend/*
            sudo cp -r ~/fullstk-app/react-frontend/build/* /var/www/frontend/
            
            # Restart backend
            pkill -f 'java -jar' || true
            nohup java -jar ~/fullstk-app/spring-boot-backend/target/*.jar > backend.log 2>&1 &
            echo "Deployment successful!"